export default [
    { "_id": "A101", "title": "Propulsion Assignment", "course": "RS101" },
    { "_id": "A102", "title": "Combustion Analysis", "course": "RS101" },
    { "_id": "A103", "title": "Nozzle Design Project", "course": "RS101" },
    { "_id": "A201", "title": "Aerodynamics Quiz", "course": "RS102" },
    { "_id": "A202", "title": "Flow Analysis", "course": "RS102" },
    { "_id": "A203", "title": "Heating Analysis", "course": "RS102" },
    { "_id": "A301", "title": "Structural Design Task", "course": "RS103" },
    { "_id": "A302", "title": "Orbital Calculations", "course": "RS103" },
    { "_id": "A303", "title": "Systems Engineering Exam", "course": "RS103" },
    { "_id": "A401", "title": "Organic Synthesis Lab", "course": "RS104" },
    { "_id": "A402", "title": "Functional Groups Quiz", "course": "RS104" },
    { "_id": "A403", "title": "Spectroscopy Analysis", "course": "RS104" },
    { "_id": "A501", "title": "Coordination Compounds Lab", "course": "RS105" },
    { "_id": "A502", "title": "Crystal Field Theory Assignment", "course": "RS105" },
    { "_id": "A503", "title": "Bioinorganic Essay", "course": "RS105" },
    { "_id": "A601", "title": "Thermodynamics Problem Set", "course": "RS106" },
    { "_id": "A602", "title": "Kinetics Exam", "course": "RS106" },
    { "_id": "A603", "title": "Quantum Chemistry Project", "course": "RS106" },
    { "_id": "A701", "title": "Elvish Translation", "course": "RS107" },
    { "_id": "A702", "title": "Dwarvish Runes Exercise", "course": "RS107" },
    { "_id": "A703", "title": "Language Evolution Essay", "course": "RS107" },
    { "_id": "A801", "title": "Council of Elrond Analysis", "course": "RS108" },
    { "_id": "A802", "title": "Alliance History Paper", "course": "RS108" },
    { "_id": "A803", "title": "Diplomacy Case Study", "course": "RS108" }
]